#!/bin/sh /etc/rc.common

START=50
USE_PROCD=1

start_service() {
    local enabled
    config_load telnet
    config_get_bool enabled main enabled 1

    [ "$enabled" = "0" ] && return 0

    procd_open_instance
    procd_set_param command /usr/sbin/telnetd -l /bin/login -F
    procd_close_instance
}
