#!/bin/sh
. /lib/functions.sh
. /lib/functions/system.sh
fpart=factory
grep -q '"Factory"' /proc/mtd && fpart=Factory
if [ -e "/dev/mtd0" ]; then
wifi_mac="$(mtd_get_mac_binary "$fpart" 0x4)"
elif [ -e "/dev/mmcblk0" ]; then
wifi_mac="$(mmc_get_mac_binary "$fpart" 0x4)"
else
echo "Error: unsupported flash."
exit 1
fi
echo "$wifi_mac" | awk '{print toupper($0)}'