#!/bin/sh
. /lib/functions/caldata.sh
if [ -e "/dev/mtd0" ]; then
part="$(find_mtd_part factory)"
elif [ -e "/dev/mmcblk0" ]; then
part="$(find_mmc_part factory)"
fi
[ -n "$part" ] || { echo "Partition 'factory' not found!"; exit 1; }
mac="$1"
validate_data macaddr "$mac" >"/dev/null" 2>&1 || { echo "Please specify a correct MAC address!"; exit 1; }
dd if="$part" of="/tmp/factory.backup" 2>"/dev/null"
caldata_patch_mac "$mac" "0x4" "" "/tmp/factory.backup" 2>"/dev/null"
if [ -e "/dev/mtd0" ]; then
mtd -qq write "/tmp/factory.backup" "factory"
else
dd if="/tmp/factory.backup" of="$part" bs=512 conv=fsync 2>"/dev/null"
fi
rm -rf "/tmp/factory.backup"
rm -rf "/overlay/upper/lib/firmware"/MT762*_PALNA_EEPROM.bin